:rocket: Improve OpenCV installation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,7 +4,7 @@
 #
 # Copyright (c) Marcos Gomes-Borges
 
-VERSION="1.0.0"
+VERSION="1.1.0"
 PREFIX="${HOME}"
 
 red="\033[91m%b\033[39m"
@@ -742,15 +742,27 @@ devsetup_install_code_extensions() {
 }
 
 devsetup_install_opencv() {
-    OPENCV_VERSION="4.2.0"
-
-    printf "${magenta}" "Install OpenCV with Python and Qt support\n"
+    if [[ -z "${OPENCV_VERSION+x}" ]]; then
+        printf "${magenta}" "Choose a version using the command below:"
+        printf '
+            export OPENCV_VERSION="4.3.0"
+            export OPENCV_VERSION="4.2.0"
+            export OPENCV_VERSION="4.1.2"
+            export OPENCV_VERSION="3.4.10"
+        '
+        printf "${red}" "\nError: "
+        printf "OpenCV version not defined!\n"
+        exit 1
+    else
+        printf "${magenta}" "Install OpenCV ${OPENCV_VERSION} with Python and Qt support\n"
+        wait_for_user
+    fi
 
     homebrew_update
 
     printf "${magenta}" "Installing Opencv dependencies\n"
     brew install cmake pkg-config ceres-solver eigen ffmpeg glog \
-                 harfbuzz jpeg libpng libtiff openexr tbb || true
+                harfbuzz jpeg libpng libtiff openexr tbb || true
 
     printf "${magenta}" "Create a Python virtual environment with NumPy 1.18.1\n"
     set +u
